### ISSUE TITLE
Debug on MacOS

### ISSUE THREAD

**Issue by Winster332** [fornit1917/musili#1]
`Error running 'Default': Cannot detect dbgshim path for execute path: /Users/kusy/Documents/git/musili/WebApi/bin/Debug/netcoreapp2.1/WebApi.dll, reason: System.InvalidOperationException: Cannot detect dbgshim path for execute path: /Users/kusy/Documents/git/musili/WebApi/bin/Debug/netcoreapp2.1/WebApi.dll at JetBrains.ReSharper.Host.Features.Debugger.DebuggerWorkerConnectionListener.GetDbgShimPath (JetBrains.DataFlow.Lifetime lifetime, System.String executeAssemblyPath) [0x00070] in 35023f502c9e4294a39bb746245c55f7>:0`

shows when trying to launch web api on macos

**Comment by fornit1917** [comment]
https://rider-support.jetbrains.com/hc/en-us/community/posts/360000126224-Cannot-debug-Cannot-detect-dbgshim-path-for-execute-pat-
